version: '3.3'
services:
  airport_api:
    image: koliy82/airport_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    depends_on:
      - airport_db
  adminer:
    image: adminer:latest
    restart: always
    environment:
      - ADMINER_PLUGINS=tables-filter tinymce
      - ADMINER_DESIGN=arcs-material
    ports:
      - "8888:8888"
    depends_on:
      - airport_db
  airport_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "***"
      POSTGRES_USER: "***"
      POSTGRES_PASSWORD: "***"
    ports:
      - "54322:5432"
    volumes:
      - airport_db_data:/var/lib/postgresql/airports/data
volumes:
  airport_db_data: